services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - .envs/.env.local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - todo
  todo:
    build:
      context: .
      dockerfile: docker/local/api/Dockerfile
      additional_contexts:
        wheels: ../wheels
    image: todo:latest
    container_name: todo_api
    ports:
      - "8000:8000"
    volumes:
      - .:/todo
      - ./logs:/todo/logs
    env_file:
      - .envs/.env.local
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - todo
networks:
  todo:
    driver: bridge
volumes:
  postgres_data: